[package]
name = "leash-ai-backend-pip"
version = "0.1.0"
edition = "2021"

[dependencies]
leash-ai-core = { workspace = true }
leash-ai-backend = { workspace = true }
leash-ai-venv = { workspace = true }
tokio = { workspace = true }
async-trait = "0.1"

[dev-dependencies]
tempfile = { workspace = true }
